# Flow
# 1. Checkout, install PHP and Composer
# 2. 

name: 'Psalm'

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: false
        default: './psalm.dist.xml'
      strict:
        type: boolean
        description: 'Will fail job if Psalm found some errors (default behavior)'
        required: false
        default: true
      version-constraint:
        type: string
        description: 'Release tag of tool'
        required: false
        default: 'latest'
      reports-artifact-name:
        type: string
        required: false
        default: 'psalm-reports'

env:
  REPORT_DIR: /tmp/${{ github.run_id }}/

jobs:
  run:
    permissions:
      contents: read
    name: 'Running Psalm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Installing PHP'
        uses: shivammathur/setup-php@v2
        with:
          tools: composer

      - name: 'Installing Psalm & dependencies'
        run: |
          composer global require vimeo/psalm:${{ inputs.version-constraint }}
          composer install --no-interaction --no-progress --prefer-dist

      # - name: 'Installing Psalm'
      #   run: |
      #     wget \
      #       -O /usr/local/bin/psalm \
      #       https://github.com/vimeo/psalm/releases/download/${{ inputs.version-constraint }}/psalm.phar; \
      #     chmod +x /usr/local/bin/psalm; \
      #     psalm --version; \
      #     mkdir -p ${{ env.REPORT_DIR }};

      - name: 'Executing Psalm'
        run: |
          dynamic_command=(
            "psalm"
            "--config=${{ inputs.configuration }}"
            "--memory-limit=-1"
            "--threads=$(nproc)"
            "--long-progress"
            "--no-cache"
            "--output-format=github"
            "--report=${{ env.REPORT_DIR }}psalm.sarif"
            "--report=${{ env.REPORT_DIR }}sonarqube.json"
            "--report=${{ env.REPORT_DIR }}codeclimate.json"
          );
          if [ '${{ inputs.strict }}' = 'false' ]
          then
            "${dynamic_command[@]}" | true;
          else
            "${dynamic_command[@]}"
          fi

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ inputs.reports-artifact-name }}
          path: ${{ env.REPORT_DIR }}
          if-no-files-found: error
